CREATE TABLE IF NOT EXISTS public.match
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    sport integer,
    description character varying(255),
    match_date date,
    match_time time without time zone,
    team_a character varying(255),
    team_b character varying(255),
    CONSTRAINT match_pkey PRIMARY KEY (id)
    )
                    WITH (
                        OIDS = FALSE
                        );

CREATE TABLE IF NOT EXISTS public.match_odd
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    odd double precision,
    specifier character varying(255),
    match_id bigint,
    CONSTRAINT match_odd_pkey PRIMARY KEY (id),
    CONSTRAINT fkdqu478lvf4d2uv3spyrhf4124 FOREIGN KEY (match_id)
    REFERENCES public.match (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    )
    WITH (
        OIDS = FALSE
        );

INSERT INTO match (id, sport, description, match_date ,match_time, team_a, team_b)
values (1, 0, 'OSFP-AEK', '2021-02-12', '19:00', 'OSFP', 'AEK'),
       (2, 0, 'OSFP-PAOK', '2021-03-23', '19:30', 'OSFP', 'PAOK'),
       (3, 0, 'OSFP-PAO', '2021-04-21', '18:00', 'OSFP', 'PAO'),
       (4, 1, 'PAO-ARIS', '2021-07-10', '20:00', 'PAO', 'ARIS'),
       (5, 1, 'PAOK-AEK', '2021-10-10', '19:30', 'PAOK', 'AEK');

INSERT INTO match_odd (id, match_id, specifier, odd)
values (1, 1, '1', '1.80'),(2, 1, 'X', '3.00'),(3, 1, '2', '2.70'),
       (4, 2, '1', '1.90'),(5, 2, 'X', '3.20'),(6, 2, '2', '2.50'),
       (7, 3, '1', '1.50'),(8, 3, 'X', '3.50'),(9, 3, '2', '3.90'),
       (10, 4, '1', '1.80'),(11, 4, 'X', '3.00'),(12, 4, '2', '2.20'),
       (13, 5, '1', '1.80'),(14, 5, 'X', '3.00'),(15, 5, '2', '2.20');

CREATE SEQUENCE IF NOT EXISTS public.match_odd_seq
    INCREMENT 1
    START 16
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

CREATE SEQUENCE IF NOT EXISTS public.match_seq
    INCREMENT 1
    START 6
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;